# Generated by Django 3.2.2 on 2021-05-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0002_alter_customerenquiry_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerenquiry',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
